### ISSUE TITLE
Failed to generate part file

### ISSUE THREAD

**Issue by dokinkon** [trevorwang/retrofit.dart#99] opened 2020-01-22 05:07 UTC
**Describe the bug**
Cannot generate part file with retrofit generator.

**To Reproduce**
1. Create a new flutter app project.
2. Add retrofit dependencies in pubspec.ymal
3. Following quick start guide to declare restClient and Json POJO.
4. Type `flutter pub run build_runner build` to generate part file
5 Got following error:
```
[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] ../../.pub-cache/hosted/pub.dartlang.org/retrofit_generator-1.0.1+1/lib/src/generator.dart:271:11: Error: The getter 'isRequired' isn't defined for the class 'ParameterElement'. - 'ParameterElement' is from 'package:analyzer/dart/element/element.dart' ('../../.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.4/lib/dart/element/element.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'isRequired'.        p.isRequired ||          ^^^^^^^^^^
pub finished with exit code 78
```

**Expected behavior**
The part file can be generated without error.

**Comment by trevorwang** [comment] 2020-01-23 03:24
Can your provide the sample code ?

**Comment by zhufree** [comment] 2020-02-02 08:50
Similar problem, I don't add any pojo,the code is here: 
```
import 'package:retrofit/retrofit.dart';
import 'package:dio/dio.dart';
import 'card_item.dart';

part 'api_service.g.dart';

@RestApi(baseUrl: "https://api2.bmob.cn")
abstract class RestClient {
  factory RestClient(Dio dio, {String baseUrl}) = _RestClient;

  @GET("/1/classes/CardModel")
  Future<List<CardModel>> getCards();
}
```

And I run `flutter pub run build_runner build`, then get:
```
[INFO] Generating build script...
[INFO] Generating build script completed, took 364ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 8.2s

[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] /E:/flutter/.pub-cache/hosted/pub.flutter-io.cn/retrofit_generator-1.1.0/lib/src/generator.dart:700:39: Error: The method 'getDisplayString' isn't defined for
the class 'DartType'. - 'DartType' is from 'package:analyzer/dart/element/type.dart' ('/E:/flutter/.pub-cache/hosted/pub.flutter-io.cn/analyzer-0.36.4/lib/dart/element/
type.dart').Try correcting the name to the name of an existing method, or defining a method named 'getDisplayString'.      return refer(constant.typeValue.getDisplayStr
ing());                                      ^^^^^^^^^^^^^^^^
pub finished with exit code 78
```

**Comment by trevorwang** [comment] 2020-02-03 02:03
Please provide the env variables with `flutter doctor -v`

**Comment by zhufree** [comment] 2020-02-03 02:49
Oh sorry, here is doctor message:
```
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.10586], locale zh-CN)
    • Flutter version 1.12.13+hotfix.7 at E:\flutter
    • Framework revision 9f5ff2306b (7 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:\Android\SDK
    • Java binary at: H:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at H:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

```

**Comment by trevorwang** [comment] 2020-02-03 03:36
Here's the generated file on my Macbook.

```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'api_service.dart';

// **************************************************************************
// RetrofitGenerator
// **************************************************************************

class _RestClient implements RestClient {
  _RestClient(this._dio, {this.baseUrl}) {
    ArgumentError.checkNotNull(_dio, '_dio');
    this.baseUrl ??= 'https://api2.bmob.cn';
  }

  final Dio _dio;

  String baseUrl;

  @override
  getCards() async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final Response<List<dynamic>> _result = await _dio.request(
        '/1/classes/CardModel',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'GET',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: baseUrl),
        data: _data);
    var value = _result.data
        .map((dynamic i) => CardModel.fromJson(i as Map<String, dynamic>))
        .toList();
    return Future.value(value);
  }
}

```

**Comment by trevorwang** [comment] 2020-02-04 15:20
I close this issue. Please open it  if any question.

**Comment by MigoTiti** [comment] 2020-02-07 12:42
I had the same problem. Then i went to the generator.dart file and edited it manually, changing

`return refer(constant.typeValue.getDisplayString());` 
in line 700 to
`return refer(constant.typeValue.displayName);`

 and it worked.

**Comment by trevorwang** [comment] 2020-02-08 05:22
Can you provide your dart version and sample code?

**Closed** 2020-02-09 07:51 UTC
Labels: question

**Comment by tianrandailove** [comment] 2020-05-13 10:18
i have the same problem:
[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] ../../../../../../.pub-cache/hosted/pub.flutter-io.cn/retrofit_generator-1.1.0/lib/src/generator.dart:700:39: Error: The method 'getDisplayString' isn't defined for the class 'DartType'. - 'DartType' is from 'package:analyzer/dart/element/type.dart' ('../../../../../../.pub-cache/hosted/pub.flutter-io.cn/analyzer-0.36.4/lib/dart/element/type.dart').Try correcting the name to the name of an existing method, or defining a method named 'getDisplayString'.      return refer(constant.typeValue.getDisplayString());                                      ^^^^^^^^^^^^^^^^
pub finished with exit code 78

development environment :
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.17.0 at /Users/finefine/Library/flutter
    • Framework revision e6b34c2b5c (11 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

**Comment by trevorwang** [comment] 2020-05-13 10:36
Please upgrade your retrofit & generator to latest one.
