### ISSUE TITLE
throw type not mutch exception  when run build_runner

### ISSUE THREAD

**Issue by muyuballs** [trevorwang/retrofit.dart#347] opened 2021-05-28 11:08 UTC
```shell
flutter pub run build_runner build --delete-conflicting-outputs

....
type 'ExpandIterable<InterfaceType, MethodElement>' is not a subtype of type 'Iterable<MethodElementImpl>' of 'iterable'
....
```
```shell
flutter docter -v
```
```shell
[✓] Flutter (Channel stable, 2.2.0, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.0 at /home/muyu/Applications/flutter
    • Framework revision b22742018b (13 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

**Comment by NicolaVerbeeck** [comment] 2021-05-28 11:58
Duplicate of #345

**Closed by NicolaVerbeeck** 2021-05-28 11:58 UTC
