### ISSUE TITLE
build error type 'ExpandIterable<InterfaceType, MethodElement>' is not a subtype of type 'Iterable<MethodElementImpl>' of 'iterable'

### ISSUE THREAD

**Issue by eightmoons** [trevorwang/retrofit.dart#351] opened 2021-05-29 10:01 UTC
**Describe the bug**
build not succeeding

**To Reproduce**
1. create a new flutter app project
2. add dependencies
```
dependencies:
  flutter:
    sdk: flutter

  retrofit:
  dio: ^4.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  retrofit_generator:

```
3. create class
```
part 'test_api.g.dart';

@RestApi(baseUrl: "hhtp://localhost")
abstract class TestApi {
  factory TestApi(Dio dio, {String baseUrl}) = _TestApi;

  @POST("users")
  Future<HttpResponse> post();
}
```
5. run build runner 
`flutter packages pub run build_runner build`

6. see an error
```
[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 474ms

[INFO] Running build...
[INFO] Running build completed, took 11ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 36ms

[SEVERE] retrofit_generator:retrofit on lib/test_api.dart (cached):

type 'ExpandIterable<InterfaceType, MethodElement>' is not a subtype of type 'Iterable<MethodElementImpl>' of 'iterable'
[SEVERE] Failed after 64ms
pub finished with exit code 1
```
**Expected behavior**
the build should succeed

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 
 - Version10.0.19042 Build 19042

**Comment by NicolaVerbeeck** [comment] 2021-05-29 10:04
Duplicate of #345 (I have guessed the ticket number, on mobile)

**Closed** 2021-05-29 10:04 UTC
