### ISSUE TITLE
Doesn't generate

### ISSUE THREAD

**Issue by baik78** [trevorwang/retrofit.dart#348] opened 2021-05-28 11:57 UTC
**Describe the bug**
 (element.methods..addAll(element.mixins.expand((i) => i.methods))) 

type 'ExpandIterable<InterfaceType, MethodElement>' is not a subtype of type 'Iterable<MethodElementImpl>' of 'iterable'
dart:core                                                   List.addAll
package:retrofit_generator/src/generator.dart 164:25        RetrofitGenerator._parseMethods
package:retrofit_generator/src/generator.dart 88:26         RetrofitGenerator._implementClass.<fn>
package:code_builder/src/specs/class.g.dart 292:33          _$ClassBuilder.update

**To Reproduce**
try to generate

**Desktop (please complete the following information):**
 - OS: macos

**Comment by NicolaVerbeeck** [comment] 2021-05-28 11:59
Duplicate of #345

**Closed by NicolaVerbeeck** 2021-05-28 11:59 UTC
