### ISSUE TITLE
type 'ExpandIterable<InterfaceType, MethodElement>' is not a subtype of type 'Iterable<MethodElementImpl>' of 'iterable'

### ISSUE THREAD

**Issue by pablopantaleon** [trevorwang/retrofit.dart#352] opened 2021-05-29 19:45 UTC
**Describe the bug**
File generation es failing using the latest version and latest version of dart.
code:
```dart
part 'my_api.g.dart';

@RestApi()
abstract class MyApi {
  factory MyApi(Dio dio, {String baseUrl}) = _MyApi;
}
```

pubspec:
```
  # network
  dio: ^4.0.0
  retrofit: ^2.0.0
  json_annotation: ^4.0.1

  # internal
  domain:
    path: ../domain

dev_dependencies:
  build_runner: ^2.0.4

  # network
  retrofit_generator: ^2.0.0
  json_serializable: ^4.1.3

  # testing
  mockito: ^5.0.9
  test: ^1.17.5
```

**output**
[INFO] Running build...
[INFO] 2.1s elapsed, 0/1 actions completed.
[SEVERE] retrofit_generator:retrofit on lib/datasources/my_api.dart:

type 'ExpandIterable<InterfaceType, MethodElement>' is not a subtype of type 'Iterable<MethodElementImpl>' of 'iterable'
[INFO] Running build completed, took 2.5s

**To Reproduce**
1. just run the following command
`flutter pub run build_runner build --delete-conflicting-outputs`

**Expected behavior**
Should generate the respective file

**Doctor**
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.2.3 20D91 darwin-x64, locale en-GT)
    • Flutter version 2.2.0 at /*/
    • Framework revision b22742018b (2 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/preyes/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.77

-------

also i tried upgrading to version
```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.2.3 20D91 darwin-x64, locale en-GT)
    • Flutter version 2.2.1 at /*/
    • Framework revision 02c026b03c (2 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1
```
but i get the same output

**Comment by NicolaVerbeeck** [comment] 2021-05-29 19:47
Duplicate of #345

**Closed by NicolaVerbeeck** 2021-05-29 19:48 UTC
