### ISSUE TITLE
Allow empty param for method annotation

### ISSUE THREAD

**Issue by dungnv2602** [trevorwang/retrofit.dart#69] opened 2019-10-06 16:24 UTC
The picture spoke itself
![take_02](https://user-images.githubusercontent.com/19910775/66272171-76f1bf00-e890-11e9-8fb2-a5c29158f0f2.png)

Right now I have to input empty String which is silly of course.

**Comment by trevorwang** [comment] 2019-10-28 03:01
Hi @dungnv2602  

I don't think it's a correct way to add resource name to base URL

please refer to 

https://github.com/trevorwang/retrofit.dart/blob/3e98f69271294f707766247491225673680b5f25/example/lib/example.dart#L8

Please reopen this issue if any question

**Comment by dungnv2602** [comment] 2019-10-28 06:12
I combined your package with Dio, real baseUrl is put in Dio configurations. I did it and it worked normally. Doing this can scales well when you had another separated class which has 'baseUrl' for example '/novels' which still share the same baseUrl. The problem maybe is in the name 'baseUrl' itself.

**Comment by trevorwang** [comment] 2019-10-28 07:52
What you did is to separate each resource to one class.  It's not recommended by this library.

I reopen this issue but mark this as wontfix

**Comment by dungnv2602** [comment] 2019-10-28 13:17
So you saying I have to put everything inside one class, don't you worry it will bulk up when doing that?
And If I have a bunch of methods related to '/posts', I have to add '/posts/' inside every method?

In your example, you put '/tasks/' in every method related to '/tasks' because of this pattern. 
And you even put another URL 'http://httpbin.org'  which is from another website over two methods. Remember the baseUrl above is "https://5d42a6e2bc64f90014a56ca0.mockapi.io/api/v1/". 

So what is the point of this mess? Is it consistent or not?

What I want is a class specifically for 'posts' CRUD, a class specifically for 'tasks' CRUD, not put all of them inside one class. And they share the same baseUrl.

**Comment by trevorwang** [comment] 2019-10-29 11:07
Adding the resource name to each request is recommended even you want to separate to different classes.

What you did does work but it is not by design of this framework.

**Closed** 2019-11-08 10:25 UTC
