### ISSUE TITLE
Cannot explicitly pass null to a map or class @Body

### ISSUE THREAD

**Issue by daveols** [trevorwang/retrofit.dart#283] opened 2020-12-14 11:34 UTC
I want to be able to explicitly pass `null` in a `PATCH` request body:

```json
{
  "example": null
}
```

As far as I can tell, the changes merged in #237 now prevent this from being possible due to the `removeWhere` line that is injected after `toJson` is run on the map or class.

Is there a workaround for this? I think it would be great if there was a way to have better control over which fields are removed from the request.

**Comment by alexaf2000** [comment] 2020-12-14 22:14
Have you tried with an empty `String`? Most of the back-end server languages assumess an empty `String` as `null`, maybe this way you can do the request.

**Comment by daveols** [comment] 2020-12-14 22:54
Thanks for the suggestion @alexaf2000 - unfortunately the field in question is of type `int` so submitting an empty string throws a validation error.

**Comment by alexaf2000** [comment] 2020-12-14 22:59
Ups... That's sounds bad 😰! I supposed that you have been tried using `0` then? Is a ugly/temporal solution, but maybe can work

**Comment by daveols** [comment] 2020-12-15 04:34
No luck, the API accepts `null` and positive `int` that corresponds to an entity ID.

**Comment by woprandi** [comment] 2020-12-16 15:28
I don't understand why want to remove null values, that should be the job of the serializer. JsonSerializable already have an option to not include null...

**Comment by nirbar89** [comment] 2021-01-12 21:57
i'm also dealing with this issue...

the problem is in this line in the generated file:
_data.removeWhere((k, v) => v == null);

as @woprandi says this job need to be done with JsonSerializable

in my case i need to pass JSON with two keys first one with string and second one sometimes with null or string to my backend 

unfortunately i cant do it...

**Comment by woprandi** [comment] 2021-01-16 15:18
I opened a PR to fix that : https://github.com/trevorwang/retrofit.dart/pull/298

**Comment by woprandi** [comment] 2021-01-22 08:42
1.4.1+2 has been released with a fix

**Closed** 2021-06-11 02:03 UTC
Labels: wontfix
